### ISSUE TITLE
重构一下代码吧

### ISSUE THREAD

**Issue by chucai** [jpush/jpush-api-ruby-client#12]
代码问题太多了：名称定义有问题，各种if 判断，还有完全没有按照ruby的命名规则定义...
实例代码也有问题

**Comment by Martin288** [comment]
重构一下代码吧！！！！！！！！！各种恶心的变量名跟使用规范，浓浓的 Java 味道

**Comment by helperhaps** [comment]
你们说的很正确，我们正在重构代码，感谢建议
