### ISSUE TITLE
希望能够尽量避免使用build 类似的语法

### ISSUE THREAD

**Issue by wahyd4** [jpush/jpush-api-ruby-client#20]
```ruby
jpush = JPush::Client.new(app_key, master_secret)

    audience = JPush::Push::Audience.new
    audience.set_alias(user_id)
    audience.build
    
    notification = JPush::Push::Notification.new
                       .set_ios(alert: '', sound: nil, badge: nil, available: nil, category: nil, extras: {start_time: start_time})
                       .build

    payload =JPush::Push::PushPayload.new(platform: 'ios',
                                    audience: audience,
                                    notification: notification).build

    result = jpush.pusher.push(payload)
```
我说一点个人建议：
在使用了master分支的代码之后，我大致有这样可能工作的代码。但是这里面 Audience, Notification, PushPayload, 对象需要build， 而 Client 又不需要build, 有点困惑。

能否统一去掉.build 这样的语句呢? 因为执行.new 的时候已经返回 本对象的一个实例了，然而build 依然还是返回该对象实例， 这种方式就给人感觉很奇怪，对象类型都一致了，然后还要build?

 这个语法感觉更像是java 的方式, 而不是ruby的方式。然而在java 里面通常比如StringBuild 对象，.build() 之后会返回一个String 对象，而不是StringBuilder 对象本身。

此外感觉你们最近，代码变化太大，太快了。 rubygem 官网的版本， rdoc 网站的文档， github 大家看到的版本、文档，jpush 官网看到的示例，不太一致。给人感觉很困惑。无从选择，希望能够优化。

**Comment by helperhaps** [comment]
ruby sdk 是最近重写的，所以变化会很大，之前的 v3 版本已经基本不再支持。关于文档的问题，是有些混乱，

关于这个 build 方法，你说的很有道理，我也觉得不好，有些累赘，不过我还没想好怎么去做，你有什么建议

**Comment by wahyd4** [comment]
比如在
```ruby
 payload =JPush::Push::PushPayload.new(platform: 'ios',
                                    audience: audience,
                                    notification: notification).build
```
可以让 playload 自己去做build 相关的操作，这样，就不用显示让用户自己手动调用了

**Comment by helperhaps** [comment]
我们的目的很明确了，就是不需要手动的去调用这个 build 方法，具体代码实现上有什么想法没，

**Comment by wahyd4** [comment]
我的想法可能不是很好。  

我上面意思是： build 方法可以看作是做了一些数据处理和准备工作。 这些工作是必须的，我们可以在PushPayload 对象实例化之后，让pushpayload去一一调用这些数据准备工作。对外而言，我们看不到任何调用操作。PushPayload 自己就悄然无息的完成了。

**Comment by helperhaps** [comment]
你说的话我都理解，这个是正确的思路，我尽量会在下个版本的时候去掉所有的 build 方法。

**Comment by helperhaps** [comment]
@wahyd4 我已经想好怎么做了，只不过到时候你们又要改代码了去掉那个 build 方法

**Comment by wahyd4** [comment]
@helperhaps  这个无所谓，只要api变得越来越好用

**Comment by helperhaps** [comment]
@wahyd4 你现在就可以使用 dev 分支的代码，build 方法已经全部去掉了， 刚刚突然发现，之前的readme 在 schedule api 要使用 build 方法，但是我的文档中没有提到。。。
