### ISSUE TITLE
push_payload.to_hash 的值是nil

### ISSUE THREAD

**Issue by towonzhou** [jpush/jpush-api-ruby-client#24]
![image](https://cloud.githubusercontent.com/assets/1267017/15008784/3ead7ca6-1215-11e6-88e2-b2555fb9e50d.png)

**Comment by helperhaps** [comment]
我刚刚在没命令行下试了一下，没有问题，请问你使用的版本是不是最新的 4.0.2 呢

**Comment by towonzhou** [comment]
是4.0.1

**Comment by helperhaps** [comment]
4.0.1 是会有这个问题的，请升级至最新版本 4.0.2 就 OK了

**Comment by towonzhou** [comment]
@helperhaps 还有 请问往ios的dev环境发送参数应该怎么配置

**Comment by helperhaps** [comment]
默认就是开发环境，直接发送应该没有问题， 若是生产环境需要查看[http://docs.jpush.io/server/rest_api_v3_push/#options](http://docs.jpush.io/server/rest_api_v3_push/#options) 文档，或者你看 [README](https://github.com/jpush/jpush-api-ruby-client/blob/master/docs/Guides.md#推送可选项) 中有相关说明

**Comment by towonzhou** [comment]
@helperhaps registration_id 这个怎么获得啊

**Comment by helperhaps** [comment]
请查看相关文档 [我是文档](http://docs.jpush.io/client/android_api/#registrationid-api)
简单来说 registration_id 的获取不是服务端的业务功能
