### ISSUE TITLE
为什么要把ruby的版本限定在2.2呢

### ISSUE THREAD

**Issue by charleyw** [jpush/jpush-api-ruby-client#27]
我们的服务器上使用的ruby版本是2.1

但是咱们这个的gem限定ruby版本2.2，是有什么特殊理由吗？

为了这个gem是升级服务器上的版本，我感觉比较危险。

能降低一些吗?

**Comment by helperhaps** [comment]
@charleyw 写 SDK 的时候不知道哈系参数是 2.2 才加入进来的的，就在 SDK 中大量使用了这个特性（我的本地版本是 2.3 所以测试也没问题），如果要兼容 2.1 以下的话，不知道怎么去做 :sob:  

而且
> We are planning to release Ruby 2.1.9 by the end of March. After the release, we will end the normal maintenance phase of 2.1, and start the security maintenance phase of it. This means that after the release of 2.1.9 we will never backport any bug fixes to 2.1 except security fixes.

> We recommend that you start planning to upgrade to Ruby 2.3 or 2.2.

> 摘自 [Ruby-lang](https://www.ruby-lang.org/en/news/2016/02/24/support-plan-of-ruby-2-0-0-and-2-1/)

Ruby 官方已不再支持 2.1 版，所以最好的方式是升级你的 Ruby 版本，当然如果你有好的方式，来让 SDK 能够支持较低的版本，也请告诉我。

**Comment by charleyw** [comment]
我最后还是 升级了。
