### ISSUE TITLE
apns_production: true

### ISSUE THREAD

**Issue by MoonShining** [jpush/jpush-api-ruby-client#29]
一直收不到推送，看到文档很下面才发现，默认的环境是 apns_production: true

建议修改一下默认环境，或者把这个选项放在文档中更显眼的位置

**Comment by helperhaps** [comment]
默认环境是 True？哪个文档？

**Comment by MoonShining** [comment]
https://github.com/jpush/jpush-api-ruby-client/blob/master/docs/Guides.md#push-api ＝> 构建 PushPayload 对象

```
构建 PushPayload 对象

一个推送对象，表示一条推送相关的所有信息，通知内容体。是被推送到客户端的内容。 notification 和 message 二者必须有其一，可以二者并存。 如果目标平台有 iOS 平台 需要在 options 中通过 apns_production 字段来制定推送环境。True 表示推送生产环境，False 表示要推送开发环境； 如果不指定则为推送生产环境。
```

**Comment by helperhaps** [comment]
哈，这个是我的锅，现在的逻辑是只有你有效调用 set_options 方法且没有设置 apns 环境才会默认 false，就是说没有调用这个方法的话 apns 的参数是空即 nil 来的。所以就会有你所说的情况发生了，我将会在下一个版本中默认设置 apns。

**Comment by helperhaps** [comment]
如果我的回答已经解决你的问题，那么这个 issue 我就关了哈

**Comment by MoonShining** [comment]
ok!

**Comment by MoonShining** [comment]
ok! @helperhaps

**Comment by helperhaps** [comment]
遇到任何开发问题欢迎开 issue 讨论，如果和开发代码逻辑无关也可以来[极光社区](https://community.jiguang.cn/)搜索解决或发帖咨询，我们致力于解决开发者开发过程中的任何问题
