### ISSUE TITLE
请教一个问题：“发送通知” 和 “自定义消息”的区别

### ISSUE THREAD

**Issue by chucai** [jpush/jpush-api-ruby-client#30]
发送通知的api 是 `JPush::Push::Notification` 吗？

**Comment by helperhaps** [comment]
> 不知道下图能否解决你的疑问（图片来自极光文档）

![screenshot_2016-09-23_10-03-31](https://cloud.githubusercontent.com/assets/8064048/18771871/0a118f44-8175-11e6-8ff4-c99113022844.png)

> ps： 
请看 README 使用 SDK ，另外业务上有不懂的地方请先看[文档](http://docs.jiguang.cn/jpush/guideline/intro/) 再有不明白的可以去极光社区提问 https://community.jiguang.cn/

**Comment by helperhaps** [comment]
@chucai 不知解决你的疑问没有，如果解决那这个 issue 我关了
