### ISSUE TITLE
undef_method :blank? error in rails5 + factory_girl

### ISSUE THREAD

**Issue by cao7113** [jpush/jpush-api-ruby-client#31]
There was an error when trying to load the gem 'factory_girl'

we find after refine Object#blank?, load factory_girl gem error

ref https://github.com/thoughtbot/factory_girl_rails/issues/215

refine syntax does not wok well with undef_method

**Comment by helperhaps** [comment]
yeah it can be that.

在 Genfile 文件中把本 gem 置于 factory_girl 之后可以解决这个 error。我不晓得到底是这边的错（refine）还是 factory 的错，因为在 Rails 4 的环境下两个是兼容的。难道说不要使用 Refinement

**Comment by cao7113** [comment]
作者回复好快，解决啦，多谢！

**Comment by helperhaps** [comment]
Why English :smile: 

恩，其实现在貌似也就和 factory-girl 相性不合

遇到任何开发问题欢迎开 issue 讨论，如果和开发代码逻辑无关也可以来[极光社区](https://community.jiguang.cn/)搜索解决或发帖咨询，我们致力于解决开发者开发过程中的任何问题。
