### ISSUE TITLE
refine 语法建议去掉

### ISSUE THREAD

**Issue by menghuanwd** [jpush/jpush-api-ruby-client#33]
@cao7113 我也赞同你说的，refine 会和很多gem冲突，，比如railsadmin

**Comment by helperhaps** [comment]
@menghuanwd 既然这么多人都说了，我觉得也不是没有道理，之前是图省事所以直接从 Rails 借鉴一些简单好用的方法过来直接用，而且也不是暴露在外的，那么问题来了，阁下有兴趣过来提个 PR 吗，让我们一起来完成这个事

**Comment by menghuanwd** [comment]
@helperhaps 最近的那朋友的PR你又不愿意merge进去

**Comment by helperhaps** [comment]
那个没有解决根本问题啊，你要看到我重定义了好几个函数，他只是换了名字而已，我觉得如果要动他的话，那整个文件都要删掉的。

既然你不方便修改的话，那就只有我来了，不过可能要等一段时间，并且我认识到之前代码的一些问题，也会着手做一些修改。

**Comment by helperhaps** [comment]
ok，你现在可以`$ bundle update` 试一下
https://github.com/jpush/jpush-api-ruby-client/releases/tag/v4.0.6
