### ISSUE TITLE
文档标识错误，不设置APNs production是推送到iOS-dev

### ISSUE THREAD

**Issue by hegwin** [jpush/jpush-api-ruby-client#35]
文档里是这么写的，但实际上如果不指定是推送到iOS-dev

![api2](https://cloud.githubusercontent.com/assets/1659895/26066430/69448680-39c9-11e7-91c8-23a2c18e2b7c.PNG)

**Comment by helperhaps** [comment]
不好意思，是这边的疏忽，官方 SDK 如果不指定这个值的话，默认为开发环境，即默认值为 false
