### ISSUE TITLE
Ruby On Rails上的使用

### ISSUE THREAD

**Issue by harry-chengdu** [jpush/jpush-api-ruby-client#38]
开发Ruby On Rails的网站向Android终端推送测试消息

，按照：
https://github.com/jpush/jpush-api-ruby-client/blob/master/docs/Guides.md#push-api
的配置说明如下：
app_key = 'xxx'  //配置为了自己的key
master_secret = 'xxx' //配置了自己的secret
jpush = JPush::Client.new(app_key, master_secret)
Push API

pusher = jpush.pusher

# simplest push Hello to all
push_payload = JPush::Push::PushPayload.new(
  platform: 'all',
  audience: 'all',
  notification: 'hello jpush',
  message: 'hello world'
)
pusher.push(push_payload)

出现
![tim 20180608094303](https://user-images.githubusercontent.com/37136831/41134925-8cda38a0-6b01-11e8-8db1-7f328a4eb65a.png)
请问是不是我哪里错了？谢谢

**Comment by helperhaps** [comment]
没出错，多读一下官方文档 https://docs.jiguang.cn/jpush/server/push/rest_api_v3_push
